install: fix

diff --git a/scripts/test1 b/scripts/test1
--- a/scripts/test1
+++ b/scripts/test1
@@ -24,11 +24,9 @@ obj="$TMP_TESTDIR/${base}_${hash}.o"
 out="$TMP_TESTDIR/${base}_${flatargs}"
 
 # Compile .o if stale
-if [ ! -f "$obj" ] || [ "$file" -nt "$obj" ]; then
-	cc -c "$file" -o "$obj" $args $COMPILE_ONLY_FLAGS || { echo "COMPILE FAILED: $base $args" >&2; exit 1; }
-fi
+cc -c "$file" -o "$obj" $args $COMPILE_ONLY_FLAGS || { echo "COMPILE FAILED: $base $args" >&2; exit 1; }
 
-export LD_LIBRARY_PATH=$REPOROOT/build/lib
+export LD_LIBRARY_PATH="$REPOROOT/build/lib"
 # Link against shared library
 cc "$obj" -o "$out" $args -L"$LD_LIBRARY_PATH" -ljstr
 
